services:

  postgres17:
    image: postgres:17.4
    container_name: postgres17
    ports:
      - 5440:5432
    volumes:
      - ../db_backup/postgres/pg17/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres123
      - TZ=Europe/Athens
    restart: always

###########################################################
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    restart: always

############################################################
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 
    restart: always